///CABECERAS///
#define SOH 0x01
#define EOT 0xFE 




///COMANDOS PARA RECIBIR
#define PUESTA_EN_HORA 0x20
#define SET_CUENTA_ATRAS 0x25
#define GET_CUENTA_ATRAS 0x35
#define CICLO_MEDIDAS 0x70
#define MEDIDAS_ALMACENADAS 0x40
#define ULTIMA_MEDIDA 0x50
#define TODAS_MEDIDAS 0x55
#define BORRAR_MEDIDAS 0x60


///COMANDOS PARA ESCRIBIR
#define PUESTA_EN_HORA_RESP 0x20
#define SET_CUENTA_ATRAS_RESP 0x25
#define GET_CUENTA_ATRAS_RESP 0x35
#define CICLO_MEDIDAS 0x70
#define MEDIDAS_ALMACENADAS_RESP 0x40
#define ULTIMA_MEDIDA 0x50
#define TODAS_MEDIDAS 0x55
#define BORRAR_MEDIDAS_RESP 0x60

